### PR TITLE
Add format rules for Python

### PR DESCRIPTION
**Pull request by urob**
- [x] This code is up-to-date with the `main` branch.
- [x] I have updated relevant (if any) areas in the docs.

This adds some baseline formatting rules for Python scripts. For now, this only affects `app_rules/generate_app_rules.py` so we could also move it there. But I like having formatter rules at the repo root to ensure consistency.

### CODE REVIEW

**Comment by dalyIsaac** [comment]
I think it'd be worth adding a GitHub Actions to check the source code, if one of the applicable directories changes?

**Comment by urob** [comment]
> I think it'd be worth adding a GitHub Actions to check the source code, if one of the applicable directories changes?

You mean just as a test that fails if any formatting is done?

**Comment by urob** [comment]
I added two commit checks that check formatting and a select few linting rules for all python files. For now, I added them to them existing commit workflow, which adds about 20s. If you prefer, we could move them to a separate workflow that runs more selectively but given how fast `ruff` is I thought it might be cleaner the way I did.

**Review by dalyIsaac — APPROVED** [review]
That looks great, thanks!

**Pull request merged**
